// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykckhkfhofdesduluiud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrY2toa2Zob2ZkZXNkdWx1aXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzU0MDcsImV4cCI6MjA2NTkxMTQwN30.rbpFNFICHb_74JCMpdC08ujqFG4-oxfDZUPHjVW9lMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);